#!/usr/bin/env python
# quick and dirty

import binascii
import hashlib
import json
import os
import random
import string
import sys


def encode_rabbit_password_hash(salt, password):
    salt_and_password = salt + password.encode('utf-8').encode('hex')
    salt_and_password = bytearray.fromhex(salt_and_password)
    salted_md5 = hashlib.sha256(salt_and_password).hexdigest()
    password_hash = bytearray.fromhex(salt + salted_md5)
    password_hash = binascii.b2a_base64(password_hash).strip()
    return password_hash

def generate_hash(password):
    letters = string.ascii_uppercase + string.ascii_lowercase
    random_string = ''.join(random.choice(letters) for i in range(4))
    salt = random_string.encode('hex')
    return encode_rabbit_password_hash(salt, password)


if __name__ == "__main__":
    with open(sys.argv[1]) as cfg:
        config = json.load(open(sys.argv[1]))
    for u in config['users']:
        if u['password_hash'].startswith("$"):
            u['password_hash'] = generate_hash(os.environ[u['password_hash'][1:]])

    print(json.dumps(config))
